{
    "name": "CRM Custom Module",
    "version": "1.0.26",
    "summary": "CRM Custom Module",
    "author": "tk dev",
    "depends": ["base", "web", "mail"],
    "external_dependencies": {
        "python": ["Pillow", "python-barcode", "boto3"],
    },
    "assets": {
        "web.assets_backend": [],
    },
    "data": [
        "security/partner_portal_groups.xml",
        "security/partner_portal_rules.xml",
        "security/ir.model.access.csv",
        "data/partner_portal_fix.xml",
        "views/partner/table_view.xml",
        "views/partner/form_view.xml",
        "views/partner/coupons_view.xml",
        "views/partner/coupon_create_wizard_view.xml",
        "views/partner/coupon_add_codes_wizard_view.xml",
        "views/partner/receipt_redeem_view.xml",
        "views/partner/portal_user_wizard_view.xml",
        "views/partner/action_view.xml",
        "views/user/table_view.xml",
        "views/user/search_view.xml",
        "views/user/partner_user_list_view.xml",
        "views/user/point_coupon_views.xml",
        "views/user/form_view.xml",
        "views/user/user_add_point_wizard_view.xml",
        "views/user/user_add_coupon_wizard_view.xml",
        "views/user/action_view.xml",
        "views/user/point_redeem_view.xml",
        "views/user/point_redeem_generate_wizard_view.xml",
        "views/system/otp_table_view.xml",
        "views/system/otp_form_view.xml",
        "views/system/otp_action_view.xml",
        "views/menu_view.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False
}
